apiVersion: v1
kind: Service
metadata:
  name: second-service
  labels:
    {{- include "via-helm-chart1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "via-helm-chart1.selectorLabels" . | nindent 4 }}
